In [1]:
import sqlglot
import sqlparse
import re

In [2]:
def remove_sql_comments(sql_code):
    # Loại bỏ tất cả các comment dạng /* */ kể cả trên nhiều dòng
    sql_code_no_block_comments = re.sub(r'/\*.*?\*/', '', sql_code, flags=re.DOTALL)
    
    # Tách đoạn mã SQL thành từng dòng
    lines = sql_code_no_block_comments.splitlines()
    
    # Xử lý từng dòng để loại bỏ comment dạng --
    cleaned_lines = []
    for line in lines:
        # Tìm vị trí ký tự comment --
        comment_index = line.find('--')
        if comment_index != -1:
            # Nếu có comment, chỉ lấy phần trước comment
            line = line[:comment_index]
        
        # Thêm dòng đã được làm sạch vào danh sách, chỉ thêm nếu dòng không trống
        if line.strip():
            cleaned_lines.append(line.strip())
    
    # Nối các dòng lại với nhau, mỗi dòng cách nhau bởi dấu xuống dòng
    return '\n'.join(cleaned_lines)

In [28]:
sql="""SELECT CAST(NULL AS NUMBER) AS GSTX_INTF__ID, CAST(br.UNQ_ID_SRC_STM AS VARCHAR2(10)) AS NFO_BRANCH_CODE, CAST(UPPER(br.IP_FULL_NM) AS VARCHAR2(100)) AS NFO_BRANCH_NAME, CAST(cstgrp.SRC_CL_ID AS VARCHAR2(10)) AS CUSTGROUP, i.IP_ID, CAST(i.UNQ_ID_SRC_STM AS VARCHAR2(50)) AS CST_ID, CAST(i.IP_FULL_NM AS VARCHAR2(100)) AS CST_FULL_NAME, CAST(st.SRC_CL_ID AS VARCHAR2(50)) AS CIF_STATUS, CAST(cst_st.DSC_VIET AS VARCHAR2(50)) AS CUSTOMER_STATUS, CAST(cst.EFF_CST_DT AS DATE) AS CIF_OPEN_DATE, CAST(lgtp.SRC_CL_ID AS VARCHAR2(50)) AS CST_LEGAL_TYPE, CAST(idv.IDENTN_NO AS VARCHAR2(20)) AS CST_LEGAL_NBR, CAST(idv.IDENTN_ISSU_DT AS DATE) AS LEGAL_APRV_DATE, COALESCE(ip.ISS_PLC, opr.ISS_PLC) AS LEGAL_APRV_ADDR, CAST(idv.IDENTN_EXPIRY_DT AS DATE) AS LEGAL_EXP_DATE, CAST(ctzn.SRC_CL_ID AS VARCHAR2(50)) AS CST_NAL, CAST(idv.BRTH_DT AS DATE) AS CST_DOB, CAST(COALESCE((COALESCE(pa2.ADR_NM, '') || ' ' || COALESCE(pa2.WARD_ID, '') || ' ' || COALESCE(cntry2.DSC_VIET, '') || ' ' || COALESCE(prv2.DSC_VIET, '')), COALESCE(pa2.ADR_NM, '')) AS VARCHAR2(100)) AS CST_CONTACT_ADDR, CAST(COALESCE((COALESCE(pa.ADR_NM, '') || ' ' || COALESCE(pa.WARD_ID, '') || ' ' || COALESCE(cntry.DSC_VIET, '') || ' ' || COALESCE(prv.DSC_VIET, '')), COALESCE(pa2.ADR_NM, '')) AS VARCHAR2(100)) AS CST_ADDR, CAST(cate.ACCT_NO AS VARCHAR2(20)) AS CST_ACCT_NBR, CAST(cate.CATEGORY_CODE AS VARCHAR2(50)) AS ACCT_CATEG, CAST(cate.CATEGORY_NAME AS VARCHAR2(100)) AS ACCT_CATEG_NAME, CAST(cate.TKTT_HANCHE AS VARCHAR2(50)) AS ACCT_RESTRICT_TYPE, CASE WHEN a.error_type = 'SAI_EMAIL' THEN '30001' WHEN a.error_type = 'SAI_GTTT' THEN '30002' WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_CMND' THEN '30003' WHEN a.error_type = 'SAI_SDT' THEN '30004' WHEN a.error_type = 'SAI_LOAI_GTTT_CMSQQD' THEN '30005' WHEN a.error_type = 'SAI_LOAI_GTTT_GKS' THEN '30006' WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_GKS' THEN '30007' WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_PASSPORT' THEN '30008' END AS ERROR_CODE, CAST(a.ERROR_TYPE AS VARCHAR2(50)) AS ERROR_DESC, CAST(kyc.SRC_CL_ID AS VARCHAR2(50)) AS KYC_STATUS_CODE, CAST(kyc.DSC_VIET AS VARCHAR2(100)) AS KYC_STATUS_DESC, CAST(upgrd.BRANCH_CODE AS VARCHAR2(50)) AS BRANCH_CODE_UPGRADE, CAST(upgrd.BRANCH_NAME AS VARCHAR2(100)) AS BRANCH_NAME_UPGRADE, CAST(upgrd.INPUTER_CODE AS VARCHAR2(50)) AS INPUTER_CODE_UPGRADE, CAST(upgrd.INPUTER_NAME AS VARCHAR2(100)) AS INPUTER_NAME_UPGRADE, CAST(upgrd.APPROVED_CODE AS VARCHAR2(50)) AS APPROVER_CODE_UPGRADE, CAST(upgrd.APPROVED_NAME AS VARCHAR2(100)) AS APPROVER_NAME_UPGRADE, 'CHUA KHAC PHUC' AS ISSUE_STATUS, CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS FIRST_IMPORT_DATE, CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS CURRENT_REPORT_DATE, CAST(CAST(NULL AS DATE) AS DATE) AS ISSUE_FINISHED_DATE, CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS ISSUE_UPDATED_DATE, CMPN_STRT_DT AS PACKAGE_UPDATE_DATE FROM IP i INNER JOIN GSTX_INTF_WRONG_INFO_CIF_LISTCIF a ON i.IP_ID = a.IP_ID LEFT JOIN IP_X_IP ixi ON i.IP_ID = ixi.SBJ_IP_ID AND ixi.IP_X_IP_TP_ID = 103000004 AND ixi.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN IP br ON ixi.OBJ_IP_ID = br.IP_ID AND br.IP_TP_ID = 104500004 LEFT JOIN IP_X_GRP ixg ON ixg.IP_ID = i.IP_ID AND ixg.IP_X_GRP_TP_ID = 103100001 AND ixg.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN CV cstgrp ON cstgrp.CL_ID = ixg.GRP_ID AND cstgrp.CL_SCM_ID = 1021 INNER JOIN CST cst ON i.IP_ID = cst.CST_ID AND CST.EFF_CST_DT >= TO_DATE(20240101, 'YYYYMMDD') LEFT JOIN CST_LCS lcs ON cst.CST_ID = lcs.CST_ID AND lcs.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN CV st ON lcs.CST_LIFE_CYC_ST_TP_ID = st.CL_ID AND st.CL_SCM_ID = 1020 LEFT JOIN CV cst_st ON cst_st.CL_ID = i.IP_LCS_TP_ID AND CST_ST.CL_SCM_ID = 2019 LEFT JOIN IDV idv ON idv.IDV_ID = i.IP_ID LEFT JOIN IDV_PRFL ip ON ip.IDV_ID = i.IP_ID AND TO_DATE('20240101', 'yyyyMMdd') >= ip.EFF_DT AND TO_DATE('20240101', 'yyyyMMdd') < ip.END_DT AND i.ip_tp_id = 104500001 LEFT JOIN ORG_PRFL opr ON i.IP_ID = opr.ORG_IP_ID AND TO_DATE('20240101', 'YYYYMMDD') >= opr.EFF_DT AND TO_DATE('20240101', 'YYYYMMDD') < opr.END_DT LEFT JOIN CV lgtp2 ON lgtp2.CL_ID = opr.IDENTN_TP_ID LEFT JOIN cv lgtp ON ip.IDENTN_TP_ID = lgtp.CL_ID AND lgtp.CL_SCM_ID = 2008 LEFT JOIN IP_X_CL ipr ON i.IP_ID = ipr.IP_ID AND ipr.IP_X_CL_TP_ID = 206800008 AND ipr.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN CV ctzn ON ipr.CL_ID = ctzn.CL_ID AND CTZN.CL_SCM_ID = 2004 LEFT JOIN IP_X_LO ixl2 ON i.IP_ID = ixl2.IP_ID AND ixl2.IP_X_LO_TP_ID = 104900007 AND ixl2.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN PST_ADR pa2 ON ixl2.LO_ID = pa2.PST_ADR_ID LEFT JOIN CV cntry2 ON cntry2.CL_ID = pa2.CTY_ID AND cntry2.CL_SCM_ID = 2004 LEFT JOIN CV prv2 ON prv2.CL_ID = pa2.CNTY_ID AND prv2.CL_SCM_ID = 2003 LEFT JOIN IP_X_LO ixl3 ON i.IP_ID = ixl3.IP_ID AND ixl3.IP_X_LO_TP_ID = 104900001 AND ixl3.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN PST_ADR pa ON ixl3.LO_ID = pa.PST_ADR_ID LEFT JOIN CV cntry ON cntry.CL_ID = pa.CTY_ID AND cntry.CL_SCM_ID = 2004 LEFT JOIN CV prv ON prv.CL_ID = pa.CNTY_ID AND prv.CL_SCM_ID = 2003 LEFT JOIN (SELECT IP_ID, ACCT_NO, CATEGORY_CODE, CATEGORY_NAME, TKTT_HANCHE FROM (SELECT cif.IP_ID AS IP_ID, cif.UNQ_ID_SRC_STM AS CIF, acct.UNQ_ID_SRC_STM AS ACCT_NO, acct.EFF_DT AS OPEN_DT, cgy.UNQ_ID_SRC_STM AS CATEGORY_CODE, cgy.DSC AS CATEGORY_NAME, tkhc1.DSC_VIET AS TKTT_HANCHE, ROW_NUMBER() OVER (PARTITION BY tktt.IP_ID ORDER BY acct.EFF_DT ASC NULLS FIRST) AS RANK FROM AR_X_IP tktt INNER JOIN AR acct ON acct.AR_ID = tktt.AR_ID LEFT JOIN IP cif ON cif.IP_ID = tktt.IP_ID LEFT JOIN AR_X_PD cate ON cate.AR_ID = acct.AR_ID AND cate.AR_X_PD_TP_ID = 102700003 AND cate.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') AND cate.SRC_STM_ID = '103900001' INNER JOIN PD cgy ON cgy.PD_ID = cate.PD_ID AND LENGTH(cgy.UNQ_ID_SRC_STM) = 4 AND cgy.UNQ_ID_SRC_STM LIKE '10%' LEFT JOIN AR_X_CL tkhc ON tkhc.AR_ID = acct.AR_ID AND tkhc.AR_X_CL_RLTNP_TP_ID = 107500046 AND tkhc.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') AND tkhc.SRC_STM_ID = '103900001' LEFT JOIN CV tkhc1 ON tkhc1.CL_ID = tkhc.CL_ID WHERE tktt.AR_X_IP_TP_ID = 100800020 AND tktt.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')) tktt WHERE RANK = 1) cate ON cate.IP_ID = i.IP_ID LEFT JOIN IP_X_CL ixc ON ixc.IP_ID = i.IP_ID AND ixc.IP_X_CL_TP_ID = 206800013 AND ixc.DATA_DT = TO_DATE('20240101', 'yyyyMMdd') LEFT JOIN CV kyc ON kyc.CL_ID = ixc.CL_ID AND kyc.CL_SCM_ID = 2123 LEFT JOIN (SELECT PKG.IP_ID, ROW_NUMBER() OVER (PARTITION BY PKG.IP_ID ORDER BY PKG.CRT_DT NULLS FIRST, PKG.DT_APPRV NULLS FIRST, PKG.LAST_ACS NULLS FIRST) AS RN, OU.UNQ_ID_SRC_STM AS BRANCH_CODE, OU.IP_FULL_NM AS BRANCH_NAME, PKG.USR_CRT AS INPUTER_CODE, PKG.USR_APRV AS APPROVED_CODE, USRCRT.IP_FULL_NM AS INPUTER_NAME, USRAPR.IP_FULL_NM AS APPROVED_NAME, PKG.CMPN_STRT_DT FROM CMPN pkg INNER JOIN IP CIF ON CIF.IP_ID = pkg.IP_ID LEFT JOIN IP OU ON OU.IP_ID = PKG.OU_ID LEFT JOIN IP USRCRT ON REGEXP_SUBSTR(USRCRT.UNQ_ID_SRC_STM, '[^@]+') = PKG.USR_CRT LEFT JOIN IP USRAPR ON REGEXP_SUBSTR(USRAPR.UNQ_ID_SRC_STM, '[^@]+') = PKG.USR_APRV WHERE TO_DATE('20240101', 'yyyyMMdd') BETWEEN pkg.EFF_DT AND pkg.END_DT AND PKG.ST_TXN = 'MAT' AND PKG.SRC_STM_ID = '103900131') upgrd ON upgrd.IP_ID = i.IP_ID AND upgrd.rn = 1 WHERE (kyc.SRC_CL_ID IS NULL OR kyc.SRC_CL_ID = '2' OR kyc.SRC_CL_ID = '3' OR kyc.SRC_CL_ID = '10') AND cstgrp.SRC_CL_ID IN ('1', '12', '13', '19') AND i.IP_LCS_TP_ID = 201900001 AND NOT br.UNQ_ID_SRC_STM IN ('VN0013004', 'VN0010179', 'VN0010176', 'VN0010178', 'VN0010177', 'VN0010168', 'VN0013000', 'VN0010133', 'VN0010001', 'VN0010182')
"""

In [29]:
import sqlparse

a = sqlglot.transpile(remove_sql_comments(sql), read='db2', write="oracle")[0]

# print(a)
formatted_sql = sqlparse.format(a, reindent=True, keyword_case='upper')
print(formatted_sql)

SELECT CAST(NULL AS NUMBER) AS GSTX_INTF__ID,
       CAST(br.UNQ_ID_SRC_STM AS VARCHAR2(10)) AS NFO_BRANCH_CODE,
       CAST(UPPER(br.IP_FULL_NM) AS VARCHAR2(100)) AS NFO_BRANCH_NAME,
       CAST(cstgrp.SRC_CL_ID AS VARCHAR2(10)) AS CUSTGROUP,
       i.IP_ID,
       CAST(i.UNQ_ID_SRC_STM AS VARCHAR2(50)) AS CST_ID,
       CAST(i.IP_FULL_NM AS VARCHAR2(100)) AS CST_FULL_NAME,
       CAST(st.SRC_CL_ID AS VARCHAR2(50)) AS CIF_STATUS,
       CAST(cst_st.DSC_VIET AS VARCHAR2(50)) AS CUSTOMER_STATUS,
       CAST(cst.EFF_CST_DT AS DATE) AS CIF_OPEN_DATE,
       CAST(lgtp.SRC_CL_ID AS VARCHAR2(50)) AS CST_LEGAL_TYPE,
       CAST(idv.IDENTN_NO AS VARCHAR2(20)) AS CST_LEGAL_NBR,
       CAST(idv.IDENTN_ISSU_DT AS DATE) AS LEGAL_APRV_DATE,
       NVL(ip.ISS_PLC, opr.ISS_PLC) AS LEGAL_APRV_ADDR,
       CAST(idv.IDENTN_EXPIRY_DT AS DATE) AS LEGAL_EXP_DATE,
       CAST(ctzn.SRC_CL_ID AS VARCHAR2(50)) AS CST_NAL,
       CAST(idv.BRTH_DT AS DATE) AS CST_DOB,
       CAST(NVL((NVL(pa2.ADR_NM, '') || ' ' || NVL(pa2.WARD_ID, '') || ' ' || NVL(cntry2.DSC_VIET, '') || ' ' || NVL(prv2.DSC_VIET, '')), NVL(pa2.ADR_NM, '')) AS VARCHAR2(100)) AS CST_CONTACT_ADDR,
       CAST(NVL((NVL(pa.ADR_NM, '') || ' ' || NVL(pa.WARD_ID, '') || ' ' || NVL(cntry.DSC_VIET, '') || ' ' || NVL(prv.DSC_VIET, '')), NVL(pa2.ADR_NM, '')) AS VARCHAR2(100)) AS CST_ADDR,
       CAST(cate.ACCT_NO AS VARCHAR2(20)) AS CST_ACCT_NBR,
       CAST(cate.CATEGORY_CODE AS VARCHAR2(50)) AS ACCT_CATEG,
       CAST(cate.CATEGORY_NAME AS VARCHAR2(100)) AS ACCT_CATEG_NAME,
       CAST(cate.TKTT_HANCHE AS VARCHAR2(50)) AS ACCT_RESTRICT_TYPE,
       CASE
           WHEN a.error_type = 'SAI_EMAIL' THEN '30001'
           WHEN a.error_type = 'SAI_GTTT' THEN '30002'
           WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_CMND' THEN '30003'
           WHEN a.error_type = 'SAI_SDT' THEN '30004'
           WHEN a.error_type = 'SAI_LOAI_GTTT_CMSQQD' THEN '30005'
           WHEN a.error_type = 'SAI_LOAI_GTTT_GKS' THEN '30006'
           WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_GKS' THEN '30007'
           WHEN a.error_type = 'SAI_NGAYSINH_NGAYCAP_PASSPORT' THEN '30008'
       END AS ERROR_CODE,
       CAST(a.ERROR_TYPE AS VARCHAR2(50)) AS ERROR_DESC,
       CAST(kyc.SRC_CL_ID AS VARCHAR2(50)) AS KYC_STATUS_CODE,
       CAST(kyc.DSC_VIET AS VARCHAR2(100)) AS KYC_STATUS_DESC,
       CAST(upgrd.BRANCH_CODE AS VARCHAR2(50)) AS BRANCH_CODE_UPGRADE,
       CAST(upgrd.BRANCH_NAME AS VARCHAR2(100)) AS BRANCH_NAME_UPGRADE,
       CAST(upgrd.INPUTER_CODE AS VARCHAR2(50)) AS INPUTER_CODE_UPGRADE,
       CAST(upgrd.INPUTER_NAME AS VARCHAR2(100)) AS INPUTER_NAME_UPGRADE,
       CAST(upgrd.APPROVED_CODE AS VARCHAR2(50)) AS APPROVER_CODE_UPGRADE,
       CAST(upgrd.APPROVED_NAME AS VARCHAR2(100)) AS APPROVER_NAME_UPGRADE,
       'CHUA KHAC PHUC' AS ISSUE_STATUS,
       CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS FIRST_IMPORT_DATE,
       CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS CURRENT_REPORT_DATE,
       CAST(CAST(NULL AS DATE) AS DATE) AS ISSUE_FINISHED_DATE,
       CAST(TO_DATE('20240101', 'yyyyMMdd') AS DATE) AS ISSUE_UPDATED_DATE,
       CMPN_STRT_DT AS PACKAGE_UPDATE_DATE
FROM IP i
INNER JOIN GSTX_INTF_WRONG_INFO_CIF_LISTCIF a ON i.IP_ID = a.IP_ID
LEFT JOIN IP_X_IP ixi ON i.IP_ID = ixi.SBJ_IP_ID
AND ixi.IP_X_IP_TP_ID = 103000004
AND ixi.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN IP br ON ixi.OBJ_IP_ID = br.IP_ID
AND br.IP_TP_ID = 104500004
LEFT JOIN IP_X_GRP ixg ON ixg.IP_ID = i.IP_ID
AND ixg.IP_X_GRP_TP_ID = 103100001
AND ixg.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN CV cstgrp ON cstgrp.CL_ID = ixg.GRP_ID
AND cstgrp.CL_SCM_ID = 1021
INNER JOIN CST cst ON i.IP_ID = cst.CST_ID
AND CST.EFF_CST_DT >= TO_DATE(20240101, 'YYYYMMDD')
LEFT JOIN CST_LCS lcs ON cst.CST_ID = lcs.CST_ID
AND lcs.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN CV st ON lcs.CST_LIFE_CYC_ST_TP_ID = st.CL_ID
AND st.CL_SCM_ID = 1020
LEFT JOIN CV cst_st ON cst_st.CL_ID = i.IP_LCS_TP_ID
AND CST_ST.CL_SCM_ID = 2019
LEFT JOIN IDV idv ON idv.IDV_ID = i.IP_ID
LEFT JOIN IDV_PRFL ip ON ip.IDV_ID = i.IP_ID
AND TO_DATE('20240101', 'yyyyMMdd') >= ip.EFF_DT
AND TO_DATE('20240101', 'yyyyMMdd') < ip.END_DT
AND i.ip_tp_id = 104500001
LEFT JOIN ORG_PRFL opr ON i.IP_ID = opr.ORG_IP_ID
AND TO_DATE('20240101', 'YYYYMMDD') >= opr.EFF_DT
AND TO_DATE('20240101', 'YYYYMMDD') < opr.END_DT
LEFT JOIN CV lgtp2 ON lgtp2.CL_ID = opr.IDENTN_TP_ID
LEFT JOIN cv lgtp ON ip.IDENTN_TP_ID = lgtp.CL_ID
AND lgtp.CL_SCM_ID = 2008
LEFT JOIN IP_X_CL ipr ON i.IP_ID = ipr.IP_ID
AND ipr.IP_X_CL_TP_ID = 206800008
AND ipr.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN CV ctzn ON ipr.CL_ID = ctzn.CL_ID
AND CTZN.CL_SCM_ID = 2004
LEFT JOIN IP_X_LO ixl2 ON i.IP_ID = ixl2.IP_ID
AND ixl2.IP_X_LO_TP_ID = 104900007
AND ixl2.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN PST_ADR pa2 ON ixl2.LO_ID = pa2.PST_ADR_ID
LEFT JOIN CV cntry2 ON cntry2.CL_ID = pa2.CTY_ID
AND cntry2.CL_SCM_ID = 2004
LEFT JOIN CV prv2 ON prv2.CL_ID = pa2.CNTY_ID
AND prv2.CL_SCM_ID = 2003
LEFT JOIN IP_X_LO ixl3 ON i.IP_ID = ixl3.IP_ID
AND ixl3.IP_X_LO_TP_ID = 104900001
AND ixl3.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN PST_ADR pa ON ixl3.LO_ID = pa.PST_ADR_ID
LEFT JOIN CV cntry ON cntry.CL_ID = pa.CTY_ID
AND cntry.CL_SCM_ID = 2004
LEFT JOIN CV prv ON prv.CL_ID = pa.CNTY_ID
AND prv.CL_SCM_ID = 2003
LEFT JOIN
  (SELECT IP_ID,
          ACCT_NO,
          CATEGORY_CODE,
          CATEGORY_NAME,
          TKTT_HANCHE
   FROM
     (SELECT cif.IP_ID AS IP_ID,
             cif.UNQ_ID_SRC_STM AS CIF,
             acct.UNQ_ID_SRC_STM AS ACCT_NO,
             acct.EFF_DT AS OPEN_DT,
             cgy.UNQ_ID_SRC_STM AS CATEGORY_CODE,
             cgy.DSC AS CATEGORY_NAME,
             tkhc1.DSC_VIET AS TKTT_HANCHE,
             ROW_NUMBER() OVER (PARTITION BY tktt.IP_ID
                                ORDER BY acct.EFF_DT ASC NULLS FIRST) AS RANK
      FROM AR_X_IP tktt
      INNER JOIN AR acct ON acct.AR_ID = tktt.AR_ID
      LEFT JOIN IP cif ON cif.IP_ID = tktt.IP_ID
      LEFT JOIN AR_X_PD cate ON cate.AR_ID = acct.AR_ID
      AND cate.AR_X_PD_TP_ID = 102700003
      AND cate.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
      AND cate.SRC_STM_ID = '103900001'
      INNER JOIN PD cgy ON cgy.PD_ID = cate.PD_ID
      AND LENGTH(cgy.UNQ_ID_SRC_STM) = 4
      AND cgy.UNQ_ID_SRC_STM LIKE '10%'
      LEFT JOIN AR_X_CL tkhc ON tkhc.AR_ID = acct.AR_ID
      AND tkhc.AR_X_CL_RLTNP_TP_ID = 107500046
      AND tkhc.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
      AND tkhc.SRC_STM_ID = '103900001'
      LEFT JOIN CV tkhc1 ON tkhc1.CL_ID = tkhc.CL_ID
      WHERE tktt.AR_X_IP_TP_ID = 100800020
        AND tktt.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')) tktt
   WHERE RANK = 1) cate ON cate.IP_ID = i.IP_ID
LEFT JOIN IP_X_CL ixc ON ixc.IP_ID = i.IP_ID
AND ixc.IP_X_CL_TP_ID = 206800013
AND ixc.DATA_DT = TO_DATE('20240101', 'yyyyMMdd')
LEFT JOIN CV kyc ON kyc.CL_ID = ixc.CL_ID
AND kyc.CL_SCM_ID = 2123
LEFT JOIN
  (SELECT PKG.IP_ID,
          ROW_NUMBER() OVER (PARTITION BY PKG.IP_ID
                             ORDER BY PKG.CRT_DT NULLS FIRST, PKG.DT_APPRV NULLS FIRST, PKG.LAST_ACS NULLS FIRST) AS RN,
          OU.UNQ_ID_SRC_STM AS BRANCH_CODE,
          OU.IP_FULL_NM AS BRANCH_NAME,
          PKG.USR_CRT AS INPUTER_CODE,
          PKG.USR_APRV AS APPROVED_CODE,
          USRCRT.IP_FULL_NM AS INPUTER_NAME,
          USRAPR.IP_FULL_NM AS APPROVED_NAME,
          PKG.CMPN_STRT_DT
   FROM CMPN pkg
   INNER JOIN IP CIF ON CIF.IP_ID = pkg.IP_ID
   LEFT JOIN IP OU ON OU.IP_ID = PKG.OU_ID
   LEFT JOIN IP USRCRT ON REGEXP_SUBSTR(USRCRT.UNQ_ID_SRC_STM, '[^@]+') = PKG.USR_CRT
   LEFT JOIN IP USRAPR ON REGEXP_SUBSTR(USRAPR.UNQ_ID_SRC_STM, '[^@]+') = PKG.USR_APRV
   WHERE TO_DATE('20240101', 'yyyyMMdd') BETWEEN pkg.EFF_DT AND pkg.END_DT
     AND PKG.ST_TXN = 'MAT'
     AND PKG.SRC_STM_ID = '103900131') upgrd ON upgrd.IP_ID = i.IP_ID
AND upgrd.rn = 1
WHERE (kyc.SRC_CL_ID IS NULL
       OR kyc.SRC_CL_ID = '2'
       OR kyc.SRC_CL_ID = '3'
       OR kyc.SRC_CL_ID = '10')
  AND cstgrp.SRC_CL_ID IN ('1',
                           '12',
                           '13',
                           '19')
  AND i.IP_LCS_TP_ID = 201900001
  AND NOT br.UNQ_ID_SRC_STM IN ('VN0013004',
                                'VN0010179',
                                'VN0010176',
                                'VN0010178',
                                'VN0010177',
                                'VN0010168',
                                'VN0013000',
                                'VN0010133',
                                'VN0010001',
                                'VN0010182')

### *************************************